url: "https://baschtubunker.be" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Baschtubunker Bern" # the name of your site, e.g. ACME Corp.
